/* =========================================================
   Shared passphrase wordlist (1000 words = 9.97 bits/word).
   Used by PassForge (generation) and PassMeter (recognizing
   wordlist-attackable passphrases). Keep the two tools in sync.
   ========================================================= */
window.LI_GENERATOR_WORDS = [
  'acorn','actor','adobe','agent','alarm','album','alert','alley','amber','anchor','ankle','antler','anvil','apple','apron','arch','arena','argon','armor','arrow',
  'aspen','atlas','attic','audio','autumn','avocado','awning','axis','bacon','badge','badger','bagel','baker','bamboo','banjo','barge','barley','basil','basket','baton',
  'beach','beacon','beak','bean','bear','beard','beaver','bell','belt','bench','berry','bicycle','birch','bison','blade','blanket','blaze','blimp','bloom','blossom',
  'bluff','board','bobcat','bolt','bonfire','bongo','bonus','book','booth','borrow','bottle','boulder','bounce','bowl','brace','braid','brain','branch','brave','bread',
  'breeze','brick','bridge','brisk','broom','brush','bubble','bucket','buddy','buffalo','bugle','bundle','bunny','burrow','butter','button','cabin','cable','cactus','camel',
  'camera','canal','candle','candy','canoe','canyon','carbon','cargo','carol','carrot','carve','castle','catfish','cedar','cellar','cello','chair','chalk','charm','chase',
  'cheek','cheer','cherry','chess','chest','chill','chime','chipmunk','chord','cider','cinder','circle','citrus','clam','clarinet','clasp','claw','clay','cliff','climb',
  'cloak','clock','cloud','clover','coach','coast','cobalt','cocoa','comet','compass','copper','coral','cotton','couch','cougar','cove','coyote','crab','cradle','craft',
  'crane','crater','crayon','creek','crest','cricket','crisp','crocus','crumb','crystal','cub','curtain','cushion','cycle','dagger','dairy','daisy','dandelion','dawn','decoy',
  'deer','delta','denim','depot','desk','dew','diesel','dill','dime','dinghy','dodge','dome','donkey','donut','dove','dozen','draft','dragon','drift','drill',
  'drum','duckling','dune','dusk','eagle','easel','echo','eclipse','eel','elbow','elder','elk','elm','ember','emerald','engine','envoy','ferry','fiddle','field',
  'finch','fjord','flame','flannel','flask','fleet','flint','flute','foam','fog','forge','fossil','fox','freckle','frost','gadget','galaxy','garlic','gecko','geyser',
  'giant','ginger','glacier','glade','glider','glow','goat','goose','gourd','granite','grape','gravel','griffin','grove','guitar','gull','gust','hammer','hamper','harbor',
  'harp','hatch','hawk','hazel','hedge','helmet','heron','hickory','hillside','hinge','holly','honey','hornet','horse','husk','ibis','icicle','igloo','inlet','iris',
  'iron','island','ivory','ivy','jacket','jade','jaguar','jasper','jelly','jigsaw','jungle','juniper','kayak','kelp','kettle','kiosk','kitten','kiwi','knapsack','knoll',
  'koala','lagoon','lantern','lapel','larch','lasso','latch','lava','leaf','ledge','lemon','lentil','levee','lilac','lily','limber','linen','lion','lizard','llama',
  'locket','locust','lodge','loft','lotus','lumber','lunar','lynx','magma','magnet','magpie','mango','mantis','maple','marble','marsh','mason','meadow','melon','mesa',
  'meteor','mint','mitten','moat','mocha','molar','monsoon','moose','morning','moss','moth','mountain','mule','mural','mustard','napkin','nectar','nettle','newt','nickel',
  'night','noodle','north','nova','nugget','nutmeg','oasis','oatmeal','ocean','ocelot','octave','olive','onion','opal','orbit','orchid','osprey','otter','owl','oxen',
  'oyster','paddle','pagoda','palm','panda','pantry','papaya','parcel','parrot','pasture','patio','peach','peanut','pebble','pecan','pelican','penguin','pepper','perch','pewter',
  'phantom','piano','pickle','pigeon','pillow','pilot','pine','pistachio','pixel','plank','plasma','plaza','plume','pocket','pond','pony','poppy','porch','portal','prairie',
  'prism','pumpkin','puppet','python','quail','quarry','quartz','quill','quilt','rabbit','raccoon','radar','radish','raft','rain','ranch','raven','reef','ribbon','ridge',
  'river','robin','rocket','rooster','rose','rudder','rune','rustic','saddle','saffron','sage','salmon','sand','sapling','satchel','scarf','scooter','scout','sedan','sequoia',
  'shale','shark','shelf','shore','shrub','sierra','silk','silo','skate','sketch','skillet','sled','sleet','sloth','smock','snail','sonar','sparrow','spice','spiral',
  'spruce','squash','squid','stable','stag','stairs','stamp','starling','static','steam','stone','stork','storm','stove','strudel','summit','sunset','swan','sweater','syrup',
  'table','tadpole','taffy','talon','tandem','tangelo','tapir','tavern','teapot','tempest','temple','terrace','thicket','thistle','thunder','tiger','timber','toad','toffee','token',
  'torch','totem','toucan','trail','tram','trench','trout','truffle','trumpet','tulip','tundra','tunnel','turnip','turtle','tusk','twig','umbrella','urchin','valley','vanilla',
  'vault','velvet','vessel','vine','violet','violin','vista','volcano','vole','waffle','wagon','walnut','walrus','wasp','waterfall','weasel','wharf','wheat','whistle','willow',
  'wind','winter','wolf','wombat','wren','yarn','yodel','yonder','zebra','zephyr','zinc','zinnia','zipper','saddlebag','marmot','falcon','gondola','harvest','lantana','mesquite',
  'abbey','alcove','almond','anthem','apricot','arbor','archway','aster','aurora','aviary','axle','azalea','backpack','ballad','balloon','banner','barn','barnacle','barrel','basalt',
  'bassoon','bayou','beagle','bedrock','beetle','bellows','beret','biscuit','blizzard','bluebell','boardwalk','bobbin','bog','bookcase','boot','bramble','brass','brewery','brim','brine',
  'bronze','brook','buckle','bud','budgie','buoy','bureau','burlap','bushel','cabbage','caboose','cadet','cairn','caldera','calf','caliper','camellia','campfire','campus','canary',
  'canvas','cape','caper','caravan','carousel','cascade','cashew','catalog','cattail','cauldron','cavern','celery','chapel','chariot','chestnut','chick','chicory','chimney','chisel','chowder',
  'cinnamon','cobbler','cobweb','coconut','cod','coil','colt','column','condor','cone','conch','cork','cornet','cosmos','cottage','cowbell','cranberry','crayfish','crescent','crevice',
  'crib','crow','crowbar','cruiser','crust','cupola','cypress','dahlia','dapple','dart','decanter','den','derby','dial','dice','dingo','dipper','ditch','dock','dogwood',
  'doily','doorbell','dory','dovetail','dragonfly','drake','drawbridge','dresser','driftwood','drizzle','duct','duffel','dugout','dumpling','eddy','eggplant','emu','ermine','espresso','estuary',
  'ewe','fable','fawn','feather','fedora','fennel','fern','ferret','fig','filly','fir','firefly','fireplace','fishhook','flagpole','flamingo','flapjack','fleece','flotilla','flour',
  'foal','foothill','footpath','fountain','foyer','freighter','frigate','fringe','frond','funnel','furrow','gale','galleon','gannet','garland','garnet','gate','gazebo','gazelle','gearbox',
  'gem','gentian','gerbil','gingham','giraffe','glen','glimmer','gloss','glowworm','gnome','goblet','goldfinch','gopher','gorge','gosling','gossamer','grackle','grain','grapevine','grotto',
  'groundhog','grouse','guava','gulch','gully','gumdrop','guppy','hail','hamlet','hammock','harmonica','harrier','hatchet','hayloft','haystack','hazelnut','headland','hearth','heather','hedgehog',
  'heirloom','helm','hemlock','hen','herring','hexagon','hillock','hive','hoof','horizon','horseshoe','hound','hourglass','hurdle','hutch','hyacinth','hydrant','ibex','iceberg','icecap',
  'incense','ingot','inkwell','isle','jackal','jackdaw','jamboree','jar','javelin','jay','jetty','jewel','jonquil','junco','kangaroo','keel','keg','kernel','kestrel','keyhole',
  'kiln','kingfisher','kite','knot','kumquat','ladle','ladybug','lamppost','lance','lapwing','larkspur','lattice','laurel','lavender','lawn','leash','lectern','leek','legume','lemur',
  'lighthouse','lime','limpet','linnet','lintel','lobster','loch','loom','loon','lupine','lute','lyre','macaw','mackerel','madrone','magnolia','mallard','mallet','mammoth','mandolin',
  'mane','mangrove','manor','mantel','marigold','marina','mariner','marlin','marmalade','marrow','marten','mastiff','meadowlark','medallion','meridian','mermaid','mica','midday','mill','millpond',
  'minnow','mistletoe','mole','mollusk','monarch','monolith','moorland','moraine','morel','mosaic','muffin','mulberry','muskrat','mussel','myrtle','narwhal','nautilus','nebula','needle','nest',
  'nightfall','nimbus','nook','notch','oak','oar','obelisk','oboe','ochre','okra','oriole','orca','outcrop','outpost','oven','overpass','owlet','oxbow','ozone','paddock',
  'pail','paisley','palette','palomino','pampas','pancake','pansy','papyrus','parakeet','parapet','parka','parsley','parsnip','partridge','pathway','peacock','peak','pearl','peat','pedal',
  'pendulum','pennant','peony','persimmon','pesto','petal','petunia','pheasant','phlox','picnic','pier','pika','pinecone','pinnacle','pinto','piston','pitchfork','plateau','platypus','plow',
  'plum','pod','pointer','polecat','pollen','pomelo','poncho','poplar','porcupine','porpoise','portico','posy','potter','prawn','primrose','privet','prow','prune','puddle','puffin'
];
